// eslint-disable-next-line import/prefer-default-export
export const productsdata = [
  {
    title: "Producto 1",
    description: "Descripción del producto 1",
    price: 19.99,
    currency: "USD",
    isAddtoCartActive: true,
    isNew: true,
    productImage: "imagen_producto_1.jpg",
    productUrl: "url_producto_1",
    stars: 4.5,
    starsReviewsCounted: 100,
    stock: 10,
  },
  {
    title: "Producto 2",
    description: "Descripción del producto 2",
    price: 29.99,
    currency: "USD",
    isAddtoCartActive: false,
    isNew: false,
    productImage: "imagen_producto_2.jpg",
    productUrl: "url_producto_2",
    stars: 3.8,
    starsReviewsCounted: 75,
    stock: 5,
  },
  {
    title: "Producto 3",
    description: "Descripción del producto 3",
    price: 39.99,
    currency: "USD",
    isAddtoCartActive: true,
    isNew: false,
    productImage: "imagen_producto_3.jpg",
    productUrl: "url_producto_3",
    stars: 4.2,
    starsReviewsCounted: 120,
    stock: 15,
  },
  {
    title: "Producto 4",
    description: "Descripción del producto 4",
    price: 49.99,
    currency: "USD",
    isAddtoCartActive: true,
    isNew: true,
    productImage: "imagen_producto_4.jpg",
    productUrl: "url_producto_4",
    stars: 4.9,
    starsReviewsCounted: 150,
    stock: 8,
  },
  {
    title: "Producto 5",
    description: "Descripción del producto 5",
    price: 59.99,
    currency: "USD",
    isAddtoCartActive: false,
    isNew: false,
    productImage: "imagen_producto_5.jpg",
    productUrl: "url_producto_5",
    stars: 3.5,
    starsReviewsCounted: 50,
    stock: 12,
  },
];
