name: Lint
on:
  push:
  pull_request:
    branches: [main, develop, 'feature/**', 'bugfix/**','hotfix/**','fix/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
      - run: yarn install
      - run: yarn lint
